### ISSUE TITLE
Discord Messages show up as empty in Minecraft

### ISSUE THREAD

**Issue by imaron85** [LimeShulkerBox/fabric-discord-chat-and-console#11]
The Minecraft to Discord part works perfectly, but all messages originating in in Discord are shown as empty in minecraft.

Am running 1.19.2 fabric server on Windows Server.

**Comment by piemanau** [comment]
Could you provide some screenshots and your config without bot token and webhook?

**Comment by imaron85** [comment]
![empty chat](https://user-images.githubusercontent.com/45713863/195859770-8db15ae5-c95a-45ec-8cb1-d3c1259bff53.png)

Config:

{
	"config_version": 2,
	"bot_token": "BOT TOKEN",
	"commands_access_roles_id": "ROLE ID",
	"update_bot_status_every": 5000,
	"chat_enabled": true,
	"chat_channel_id": "CHANNEL ID",
	"commands_in_chat_channel": true,
	"prompt_enabled": true,
	"console_enabled": true,
	"console_channel_id": "CONSOLE CHANNEL ID",
	"show_debug_logs_in_console": true,
	"show_error_logs_in_console": true,
	"show_warn_logs_in_console": true,
	"show_info_logs_in_console": true,
	"webhooks_enabled": false,
	"only_webhooks": false,
	"webhook_url": "Add webhook URL here",
	"server_starting_prompt": "Server starting",
	"server_started_prompt": "Server started",
	"server_stopping_prompt": "Server stopping",
	"server_stopped_prompt": "Server stopped",
	"send_wrong_channel_message": false,
	"send_discriminator_to_minecraft": false,
	"console_buffer_enabled": true,
	"console_buffer_amount": 2000,
	"use_alternate_path_for_skin": true
}

**Comment by imaron85** [comment]
![image](https://user-images.githubusercontent.com/45713863/195860427-8fab9da2-89a4-42f8-98f5-42a16a828b71.png)

![image](https://user-images.githubusercontent.com/45713863/195860462-241a162e-729e-4378-af43-9d53255836fa.png)

**Comment by jnovack** [comment]
Can confirm.  I thought I was doing something wrong.  Exactly the same symptoms.  Bot does not respond to any command (e.g. `/seed`) or say messages in the server (e.g. `hi`).

```
# ls -1 mods/
fabric-api-0.62.0+1.19.2.jar
fabric-carpet-1.19.1-1.4.83+v220727.jar
fabric-language-kotlin-1.8.5+kotlin.1.7.20.jar
fabricord-2.1.1.jar
krypton-0.2.1.jar
lithium-fabric-mc1.19.2-0.9.1.jar
starlight-1.1.1+fabric.ae22326.jar
worldedit-mod-7.2.12.jar
Xaeros_Minimap_22.15.1_Fabric_1.19.1.jar
XaerosWorldMap_1.28.0_Fabric_1.19.1.jar
```

The console log is also blank, just shows:

```
[Username]
```

I'm expecting it to show:
```
[Username] message
```

With both role_id as populated and empty, I get completely ignored.  I don't need the bot ignoring me.  I have a toddler who does that. :)

<img width="324" alt="image" src="https://user-images.githubusercontent.com/387006/197780496-2df71dbf-d679-4d5a-a495-59dcdafa042e.png">

**Comment by piemanau** [comment]
I have figured out some more info. As shown in the image below you are now required to enable this intent. Please enable this and try again by restarting the server and if it is still broken let me know. Cheers
![image](https://user-images.githubusercontent.com/77601849/197968991-5c0ebe36-0582-429d-b76c-901de94687b9.png)

**Comment by jnovack** [comment]
Can you enable a [Read-the-Docs ](https://github.com/readthedocs/readthedocs.org#quickstart-for-github-hosted-projects) branch or enable the wiki so I (and others) can help document?

I understand this is a commissioned project, but documentation never hurts. :)

**Comment by piemanau** [comment]
> Can you enable a [Read-the-Docs ](https://github.com/readthedocs/readthedocs.org#quickstart-for-github-hosted-projects) branch or enable the wiki so I (and others) can help document?
> 
> I understand this is a commissioned project, but documentation never hurts. :)

Can you start a new issue? We can discuss it there.
