### ISSUE TITLE
[Feature suggestions] + Cannot open pull request

### ISSUE THREAD

**Issue by Aterniad** [LimeShulkerBox/fabric-discord-chat-and-console#14]
Hey!
I find your mod is the best comparing to other Fabric-Discord alternatives.
Would like to contribute few pull requests, especially:
 - add locales
 - add multiple Discord servers support
 - minor changes as show Discord attachments and replies in-game
 - maybe other milestones you don't have time to work with
Few of these already working in my own private fork, but I think community would like those features too

Currently I don't have any permissions to push any branch to create pull request, can I have some?

**Comment by piemanau** [comment]
Hey!
I am keen for some of those ideas, some we might have to discuss a bit more within the pr's but I am happy to consider them. As for permission to create a pull request, I don't you need any however I noticed you said you had your own **private** fork, I think it not being public could be the issue.

Have a look at this link aswell https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
