### ISSUE TITLE
[Enhancement] Buffer console lines to avoid ratelimits

### ISSUE THREAD

**Issue by OneYellowLemon** [LimeShulkerBox/fabric-discord-chat-and-console#3]
Buffering console lines and sending them every 2 seconds or so would be much nicer, as currently if there are many lines being printed to console, the bot will get ratelimited and then fall behind. Check out how DiscordSRV (Spigot plugin) does it :+1:

**Comment by piemanau** [comment]
This has been put on my todo list, sorry for the late reply, been busy

**Comment by piemanau** [comment]
Added in #[cd2e4a1](https://github.com/LimeShulkerBox/fabricord/commit/cd2e4a1fdc03c4ebc61115c736b071fc0d4aed26), I will fix other bugs before uploading to CF though
