### ISSUE TITLE
Duplicate messages on discord channel

### ISSUE THREAD

**Issue by BluEagle-Dev** [LimeShulkerBox/fabric-discord-chat-and-console#4]
I've set up this mod on my server with a friend and it works almost perfectly, the only problem is that the bot sends the minecraft chat messages again which i don't want because the custom hooks with the person's skin pfp already sends the messages. We tried isolating the bot in another log channel but that makes it so discord messages don't get send to minecraft chat. I don't know what to do or how to work around it.

**Comment by BluEagleOfficial** [comment]
![image](https://user-images.githubusercontent.com/29979883/181615048-41c8abc4-11a9-42d3-ab27-5ec779c46717.png)

**Comment by piemanau** [comment]
Please provide your config while removing your bot token and webhook URL. Please also provide some images of what you mean

**Comment by imabr777** [comment]
I had the same thing, I think they mean that the messages get sent once with the webhook as the player, and then once with the bot in the format "[player] chat". I fixed it using the only_webhooks config set to true.

**Comment by piemanau** [comment]
I will assume that's what it is
