### ISSUE TITLE
Any message sent in any channel gets a response from the bot with " 

### ISSUE THREAD

**Issue by SebAl73k** [LimeShulkerBox/fabric-discord-chat-and-console#7]
![image](https://user-images.githubusercontent.com/75599446/183544244-b2e71f5a-eb2b-4b15-9956-621b8853f965.png)
This happens in every channel besides console and the specified chat log channel

**Comment by piemanau** [comment]
Please check your config and check if you have **send_wrong_channel_message** set to false
