### ISSUE TITLE
Modded advancements are not displayed properly

### ISSUE THREAD

**Issue by imabr777** [LimeShulkerBox/fabric-discord-chat-and-console#8]
Any advancements which come from a mod and were added into the game are not displayed properly in the Discord channel.
![image](https://user-images.githubusercontent.com/32424582/184501589-68215a27-beb5-43ee-b913-64673702b221.png)
The image shows an example of what is displayed. Each mod has something slightly different, but they all look somewhat similar to the screenshot.

**Comment by piemanau** [comment]
I will look info this, thanks

**Comment by piemanau** [comment]
Unfortunately I don't think this is up to me because of how the language is handled, if the mods you use support [this](https://www.curseforge.com/minecraft/mc-mods/server-translation-api) you may be able to use that for it.
